jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: echo 'abcsxx'
  Job2:
    name: Job 2
    dependencies:
      - Job1
    steps:
      - type: script
        script-content: echo 'job 2'
dependencies:
  - MyProject_TeamcitySandbox
