jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: echo 'abcsxx'
      - type: script
        script-content: echo 'now let us save it to dev branch'
      - type: script
        script-content: echo 'one more step for dev branch'
